### ISSUE TITLE
Component trigger many internet calls

### ISSUE THREAD

**Issue by elad-bar** [rroller/netgear#10]
I'm using the component for 4 devices I have,
After deep investigation of an increased number of DNS calls from the devices I found out that the component is fetching data of `FwUpdate` and `internetConnectivityStatus` which samples Google cloud,
Since the update mechism of the component is running every 30 seconds, it generates in best case scenario 5 DNS calls every 30 seconds - 14k requests a day per device!

To solve it, I suggest to perform `internetConnectivityStatus` call only once every few minutes and `FwUpdate` can be performed once a day.

It can also be based on configuration with default values.

thanks

**Comment by rroller** [comment]
Wow, thank you. I will address this asap

**Comment by elad-bar** [comment]
@rroller , checked the service sequence in the UI once again,
once logging in, there is a full request of all data, if you are activating the `auto-refresh`, it will do small calls per widget,
it gave me the idea that might assist you addressing the issue:
remove the 2 request parameters from the JSON.
If the last request time for `FwUpdate` is greater than X minutes or None - Add it just for that specific call,
same will go for the `internetConnectivityStatus` with different variable to allow 2 configurations (as firmware upgrades are less frequent than internet connectivity changes).
