### ISSUE TITLE
WAC104 fails to connect

### ISSUE THREAD

**Issue by Doug-Wyman** [rroller/netgear#16]
I think this may have to do with the UPnP of the WAC104 not being compatible. 
I have no problem with the R7800 Router.  Not a big thing but would be nice to add 
the WAC104

Logger: pynetgear.router
Source: components/netgear/router.py:53
First occurred: 1:14:30 PM (6 occurrences)
Last logged: 1:45:01 PM

login using all known port-ssl combinations failed.

**Comment by rroller** [comment]
Thanks. Little hard for me to add support because I don't have the hardware to reverse how the APIs work.

**Comment by robertboccia** [comment]
same issue with wac104 not being picked up on this integration, would be great if this worked for the wac 104's

**Comment by rroller** [comment]
Do you have the firmware version of your WAC104?

**Comment by robertboccia** [comment]
V1.0.4.21

Robert Boccia
________________________________

**Comment by rroller** [comment]
Can you try pulling in the latest [0.1.5](https://github.com/rroller/netgear/releases/tag/0.1.5) release to see if it works? I just released a fix for newer device firmware

**Comment by rroller** [comment]
Related to https://github.com/rroller/netgear/issues/14

Please follow that as I'll close this issue as a duplicate
