### ISSUE TITLE
WAX 610/620 Failed setup, will retry error

### ISSUE THREAD

**Issue by hssmith76** [rroller/netgear#18]
Not sure whether this is down to the altest updates to Home Assistant or a firmware update on the devices as it happened at similar times but I now get the following error for both my WAX devices

WARNING (MainThread) [homeassistant.config_entries] Config entry 'Wax610' for netgear_wax integration not ready yet; Retrying in background
WARNING (MainThread) [homeassistant.config_entries] Config entry 'Wax620' for netgear_wax integration not ready yet; Retrying in background

Anyone else seeing this, repeated reloads and restarts are not resolving it.

**Comment by ronrath** [comment]
I'm having the same issue since upgrading firmware on my WAX 620 and WAX 630 devices

**Comment by rroller** [comment]
I bought a new netgear wax 610 and will upgrade to the latest firmware and test with it and try to fix this issue. Will keep you posted once I get the time to work on it.

**Comment by Jster007** [comment]
Same issues with WAX615; HA integration has stopped working.
Everything returns to work correctly after WAX615 firmware downgrade.

**Comment by JoostAB** [comment]
I have three WAX610 devices. Two of them still on V10.3.2.2 and working fine. One upgraded to V10.5.0.16 and stopped working in HA (device itself works ok).

**Comment by JoostAB** [comment]
@Jster007 
> Same issues with WAX615; HA integration has stopped working. Everything returns to work correctly after WAX615 firmware downgrade.

Just an Off-Topic question: Did you have to reconfigure the device? When I click 'Boot to Backup Firmware' (to V10.3.2.2) it gives me a warning that the device will go to factory defaults... Can I load a config backup created in  V10.5.0.16?

**Comment by Jster007** [comment]
That's true, downgrade will reset configuration to factory default. 
I don't test backup configuration loading, for personal specific needs I preferred to redo all the configuration manually...

**Comment by larzn** [comment]
Same issues with WAX620 in V10.6.0.7. HA integration worked well in V10.3.2.2.
I've got this message in AP log:

> Sep  7 23:06:38 nddmp[3463]: session_and_security_handling: Invalid user privileges!!! (-1)
> Sep  7 23:06:38 nddmp[3463]: Blocking the request due to invalid session params
> Sep  7 23:06:38 nddmp[3463]: Blocking the request due to invalid session params

I use "admin" user with Read/Write access !!

**Comment by rroller** [comment]
I upgraded my new AP to the latest firmware and looked at the response. There's a new security token returned that needs to be passed as a header. I'll try to fix this soon, hopefully this weekend.

**Comment by rroller** [comment]
I got this working locally. I'll push a fix very soon.

**Comment by rroller** [comment]
Released in https://github.com/rroller/netgear/releases/tag/0.1.5

**Comment by martinhrpi** [comment]
I will test it next week with a 610 and 620

**Comment by JoostAB** [comment]
Yes! Works! Great work, thx

**Comment by sergeantbort** [comment]
Just wanted to advise I had to remove and re add to get it working after
the update.  But it does seem to be working now.

**Comment by martinhrpi** [comment]
Works perfectly again on a 610 and 620! Thank you very much!
